apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /data
        name: test-volume
  volumes:
  - name: test-volume 
    hostPath:
      path: ./data  #directory on host
      type: Directory #optional
  #   volumeMounts:
  #   - name: workdir
  #     mountPath: /usr/share/nginx/empty
  # volumes:
  # - name: workdir
  #   emptyDir: {}
  # volumeMounts:
  #     - name: someName
  #       mountPath: /somedir/on/vm/
  # volumes:
  # - name: someName
  #   hostPath:
  #     path: /somedir/on/vm/