apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app: postgres
    role: database
    tier: back
spec:
  containers:
  - name: db
    image: postgres:9.4
    env:
      - name: POSTGRES_HOST_AUTH_METHOD
        value: trust
    ports:
      - containerPort: 5432
    volumeMounts:
    - name: db-data
      mountPath: /var/lib/postgresql/data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: db-data
    hostPath:
      path: ./data
      type: DirectoryOrCreate
