version: '3'
services:
    mysql:
        image: mariadb:10.0.30
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        volumes:
            - ${DB_PATH}/mysql:/var/lib/mysql
            - ${LOG_PATH}/mysql:/var/log/mysql
            - ./mysql:/var/run/mysqld
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

