version: '3'
services:
  jenkins:
    build: .
    ports:
      - 8080:8080   # HTTP port
      - 50000:50000 # Agent port
    volumes:
      - ./home:/var/jenkins_home
    # =========================================================
    # Share Docker socket between host and guest (docker agent)
    # =========================================================
    #   - /var/run/docker.sock:/var/run/docker.sock
    # =========================================================
    environment:
      GITHUB_USERNAME: $GITHUB_USERNAME
      GITHUB_TOKEN: $GITHUB_TOKEN