version: '3'
services:
    mysql:
        image: mariadb:10.0.30
        ports:
            - 3306:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
            - ./mysql:/var/run/mysqld
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}

