version: '2'

networks:
  playground:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - playground
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - playground
